# Generated by Django 4.2.6 on 2024-03-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish", models.CharField(max_length=30)),
                ("time", models.CharField(max_length=10)),
                ("ingredients", models.TextField()),
            ],
        ),
    ]
