# Generated by Django 4.2.6 on 2024-03-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="comment",
            field=models.TextField(default=" "),
        ),
    ]
