# Generated by Django 4.2.6 on 2024-03-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_recipe_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="comment",
            field=models.CharField(max_length=100),
        ),
    ]
